### ISSUE TITLE
[BUG] HeadOwner crashes whenever I look at a player head

### ISSUE THREAD

**Issue by CoffeeUncertain730** [RappyLabyAddons/HeadOwner#9]
Whenever I look at a player head, LabyMod gives me the error message "The HudWidget "Head Owner" crashed. Please report this to...". When I check the logs I get the following error message:

`	[HudWidget] Failed to tick hud widget headowner
java.lang.ClassCastException: class dcg cannot be cast to class ddr (dcg and ddr are in unnamed module of loader net.minecraft.launchwrapper.LaunchClassLoader @4241e0f4)
	at com.rappytv.headowner.v1_20_4.SkullApiImpl$Skull.<init>(SkullApiImpl.java:45)
	at com.rappytv.headowner.v1_20_4.SkullApiImpl.getDisplay(SkullApiImpl.java:24)
	at com.rappytv.headowner.widgets.HeadOwnerHudWidget.onTick(HeadOwnerHudWidget.java:31)
	at net.labymod.api.client.gui.hud.hudwidget.HudWidget.tick(HudWidget.java:73)
	at net.labymod.api.client.gui.screen.widget.widgets.hud.HudWidgetWidget.tick(HudWidgetWidget.java:211)
	at net.labymod.api.client.gui.element.CompositeElement.tick(CompositeElement.java:111)
	at net.labymod.api.client.gui.screen.widget.AbstractWidget.tick(AbstractWidget.java:959)
	at net.labymod.api.client.gui.element.CompositeElement.tick(CompositeElement.java:111)
	at net.labymod.api.client.gui.screen.widget.AbstractWidget.tick(AbstractWidget.java:959)
	at net.labymod.api.client.gui.screen.activity.ElementActivity.tick(ElementActivity.java:98)
	at net.labymod.api.client.gui.screen.activity.Activity.tick(Activity.java:249)
	at net.labymod.core.client.gui.hud.overlay.HudWidgetOverlay.tick(HudWidgetOverlay.java:109)
	at net.labymod.core.client.gui.screen.activity.DefaultIngameActivityOverlay.tick(DefaultIngameActivityOverlay.java:217)
	at net.labymod.autogen.events.generated.bc6d80d2cc924dd7a0e59d4b57bce37c.DefaultIngameActivityOverlay-tick-GameTickEvent-95.invoke(Unknown Source)
	at net.labymod.core.event.method.DefaultSubscribeMethod.invoke(DefaultSubscribeMethod.java:54)
	at net.labymod.core.event.method.DefaultListenerRegistry.invokeMethod(DefaultListenerRegistry.java:143)
	at net.labymod.core.event.method.DefaultListenerRegistry.invokeMethod(DefaultListenerRegistry.java:79)
	at net.labymod.core.event.method.DefaultListenerRegistry.invokeListeners(DefaultListenerRegistry.java:68)
	at net.labymod.core.event.DefaultEventBus.fire(DefaultEventBus.java:54)
	at net.labymod.core.event.DefaultEventBus.fire(DefaultEventBus.java:40)
	at net.labymod.api.Laby.fireEvent(Laby.java:34)
	at evi.labyMod$fireTickEvent(SourceFile:12870)
	at evi.insert$bno000$labyMod$firePostTickEvent(SourceFile:12655)
	at evi.s(SourceFile:2067)
	at evi.d(SourceFile:1289)
	at evi.f(SourceFile:888)
	at net.minecraft.client.main.Main.main(SourceFile:265)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:217)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:70)`

Information:
OS: Windows 11
LabyMod Version: 4.1.13
Minecraft Version: 1.20.4

**Comment by RappyTV** [comment]
should be fixed ig
